### PR TITLE
1 0 stable

### PR DESCRIPTION
**Pull request by sbounmy**
Hi Jean-Philippe,

I've setup a 1-0-stable branch with travis for ppl like me who are still using spree 1.0.x.

Can you please create a 1-0-stable aswell ?

I can help you maintain the project if you want, then I will stop bothering you with pull requests ^^

I will update master with the small fixes I've done aswell.

@radar any idea why this is failling ? http://travis-ci.org/#!/sbounmy/spree_multi_lingual/builds/1088773

Thanks !

Stephane.

### CODE REVIEW

**Comment by jipiboily** [comment]
@sbounmy I will process your PR soon, sorry, I am in a bit of a rush right now...thanks for all your work! By the way, I've added you as a collaborator for this repo, so you can do the work by yourself if you prefer! :)

**Comment by sbounmy** [comment]
hi @jipiboily ! No worries, I am also working on other stuffs aswell, but I will work asap on translating spree_essential_cms which will depend on this gem. Hopefully I can get a release version soon. Thanks for the collaborator permission ! :)

**Comment by sbounmy** [comment]
I've created a separate branch for 1-0-stable, closing this PR.
btw @jipiboily do you have experience with travis ? my build is failling but green on travis..

**Comment by jipiboily** [comment]
@sbounmy: not a lot of experience with travis as I just setup my first real project with it yesterday (jipiboily/monologue). Maybe I can still help. What is passing that should not? Tell me more about your problem plz.

**Comment by sbounmy** [comment]
@jipiboily look at http://travis-ci.org/#!/sbounmy/spree_multi_lingual , the build should be red but is green (Done. Build script exited with: 0)

**Comment by jipiboily** [comment]
@sbounmy I just faced the same problem. Just restarting the build did it for me: it seems to be a Travis bug, it is still alpha after all! ;)

**Comment by jipiboily** [comment]
Hum, seems like I have the same problem: http://travis-ci.org/#!/jipiboily/spree_multi_lingual

**Comment by jipiboily** [comment]
I've asked for help on #travis (IRC)....see that:

http://cl.ly/3A2W1N3e3R3r071A0s3f

No solution for now, but might help...

**Comment by sbounmy** [comment]
Thanks @jipiboily for your help !
I will try to investigate further asap.

**Pull request closed without merging**
