### PR TITLE
Add migration migrate data for taxons

### PR DESCRIPTION
**Pull request by bricesanchez**

### CODE REVIEW

**Comment by jipiboily** [comment]
This projet looking for a maintainer. I prefer not to pull commits that I won't try my self. And it looks like this is for Spree 1.2+, does the remaining of the gem works great on 1.2.0?

**Comment by sbounmy** [comment]
Hello guys,

@jipiboily sorry for now being active for a while.
I will try my best to update my own app to spree 1.1.3 then 1.2.0.

I don't know how long it will take, but I strongly want to keep maintain this gem ;)
I will take some time to look at some pull requests this week-end.

Stephane.

**Comment by bricesanchez** [comment]
English version follows --

@jipiboily : As-tu envoyé ta proposition de mainteneur sur l'IRC de Spree ? Je suis entrain de tester le Gem pour Spree 1.2.0, il fonctionne bien dans l'ensemble, les seules problématiques seraient dans l'admin, je suis entrain d'investiguer.

Veux-tu que je créé une branch 1-2-stable pour ce gem ?

@jipiboily + @sbounmy : Pouvons-nous être plusieurs à gérer ce Gem pour le faire grandir ? 

## 

@jipiboily : Do send your maintainer request to the Spree IRC ? I'm testing this gem on a Spree 1.2.0 install. It works great, there is some minor bugs, i try to fix it. 

Can i create a '1-2-stable' branch to continue the development ?

@jipiboily + @sbounmy : Can we be more to manage this Gem to rise it?

**Comment by jipiboily** [comment]
funny thing we're all three speaking french. Anyway, do you prefer to maintain it alone @sbounmy or some help would be welcome?

After all, this is mostly your code! ;)

@bricesanchez do you have multiple Spree projects to come @ Nurun that would use that? Are you willing in maintaing it on the long term or more on the short term?

And yes, I did ask on IRC where Radar and GeekOnCoffee suggested to post on the mailing, which I did, with only one answer. He is now maintainer but does not appear to have done anything yet.

Cheers

Oh, and yes, a 1.2 branche would probably be a good idea, but I'll let @sbounmy and you decide on that! ;)

**Comment by sbounmy** [comment]
@jipiboily yeah funny, I guess we are spree devs who need most I18n ^^
I will never refuse some help :) ! As I know quite well the codebase, I will help for pull requests reviews.

**Comment by jipiboily** [comment]
Just added @bricesanchez to repo's collaborators. You are now three with @stevenjenkins 

Thank you guys for your time and dedication, I think Spree community needs this kind of extension.

**Comment by bricesanchez** [comment]
I've created a '1.2' branch with new features for spree_multi_lingual.

**Pull request merged**
