### PR TITLE
Multilingual search

### PR DESCRIPTION
**Pull request by j15e**
Based on @jipiboily solution, made it cleaner using chained method to avoid repeating spree core search logic & made cleaner SQL query building. Ref #4

### CODE REVIEW

**Comment by jipiboily** [comment]
Hey @stevenjenkins @sbounmy @bricesanchez, are you still putting some time on Spree Multi Lingual? No pressure, just want to know. If you are not, I might send another email to the Spree user list to seek a maintainer.

Sorry @j15e to slightly high-jack this PR, I do that so that it can be pulled in as soon as possible...:)

**Comment by bricesanchez** [comment]
I push some time on the 1-2 branch, there is a lot of translations tweaks who need little improvements. 

@jipiboily : Did you see this blog post : http://spreecommerce.com/blog/spree-plans-for-improving-internationalization-support

**Comment by jipiboily** [comment]
Yup, saw that. Don't know what's the current status, if they will start from scratch or not...

**Comment by j15e** [comment]
P.S. does not work with Spree 1.2, looking into a fix

**Comment by sbounmy** [comment]
@jipiboily currently trying to maintain other spree extensions, but spree_multi_lingual is definitely in my pipeline !
@bricesanchez I have a 1-3-stable branch, we should somehow sync those 2 branch

**Comment by jipiboily** [comment]
@sbounmy just to be clear, I did not want to put pressure at all. I would just love if some people could take the maintenance as I am not working with Spree at all. You are probably already having quite a bit of work with the other extensions! ;)

**Comment by sbounmy** [comment]
hi @j15e  
Nice ! I would like to merge this asap in 1-3-stable.
Could you just write a spec for this please ?
Thanks again for the pull request !

**Comment by j15e** [comment]
Would love to add specs, but won't have time for this very soon! Sorry

**Comment by sbounmy** [comment]
thanks for your work @j15e it's now in master and 1-3-stable.
The multi lingual search is great :+1: I've added the missing specs aswell :beers: 
https://github.com/jipiboily/spree_multi_lingual/commit/02904834c73003671ac5ebce74ffef6067e85e02

**Comment by jipiboily** [comment]
:+1:

**Pull request closed without merging**
